global_config:
  seed: 5959
  device: "cuda"
#  False True
  record: True
  record_id: "1 "

data_config:
  data_path: "../data/"
  dataset_name: "CIFAR10"
  iid: True

client_config:
  device: "cuda"
  batch_size: 16
  num_local_epochs: 5
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam
  client_config:
  optim_config:
    lr: 0.001
#    momentum: 0.9

fed_config:
  fraction: 0.1
  num_clients: 100
  round: 500

init_config:
  init_type: "xavier"
  init_gain: 1.0

log_config:
  log_path: "../log/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "localhost"
