global_config:
  seed: 5959
  device: cuda
  record: true
  record_id: 'Cifarala1 '
data_config:
  data_path: ../data/
  dataset_name: CIFAR10
  iid: true
client_config:
  model: Cifar10CNN
  device: cuda
  batch_size: 16
  num_local_epochs: 5
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.Adam
  optim_config:
    lr: 0.001
fed_config:
  fraction: 0.1
  num_clients: 20
  round: 100
init_config:
  init_type: xavier
  init_gain: 1.0
log_config:
  log_path: ../tensorboard/
  log_name: FL.tensorboard
  tb_port: 5252
